# Generated by Django 2.2 on 2019-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('original_url', models.CharField(max_length=50)),
                ('shortened_url', models.CharField(max_length=50)),
            ],
        ),
    ]
